### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by Martyniuk** [uroslazarevic/repo-browser-server#1]
You've mentioned **.env** file in Readme, but no description about what is stored inside and with what values it should be filled in.

Please, clarify regarding: 
- **REACT_APP_CLIENT_ID**
- **REACT_APP_CLIENT_SECRET**
- **REACT_APP_REDIRECT_URI=**

**Comment by uroslazarevic** [comment]
Hello @Martyniuk,

Thanks for checking in.
This .env file content is considered sensitive information.

If your team has provided you with `.env` config as in [repo-browser-client](https://github.com/uroslazarevic/repo-browser) , please use that same `.env` info for  populating `.env.example` vars. 

Otherwise, you have to create your own github oauth app and use the info from that place, by following [docs](https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app).

**Comment by uroslazarevic** [comment]
Issue should be resolved in [PR](https://github.com/uroslazarevic/repo-browser-server/pull/2).

**Comment by uroslazarevic** [comment]
@Martyniuk ,

Thanks for your explanation [here](https://github.com/uroslazarevic/repo-browser/issues/1).

Please feel free to close the issue if latest PR addresses it.
